project:
  type: website

website:
  title: "Mudge â€” Data Science Blog"
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/notmudge
        text: "GitHub"
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR-LINKEDIN/
        text: "LinkedIn"
        target: _blank
      - icon: envelope
        href: "mailto:you@example.com"
        text: "Email"
      - icon: bar-chart
        href: https://www.kaggle.com/alexmudge
        text: "Kaggle"
        target: _blank
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv/index.qmd
      - section: "Posts"
        contents: posts

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
    css: styles.css
    include-before-body: sidebar-header.html
