project:
  type: website
  resources:
    - sidebar-header.html

website:
  sidebar:
    style: docked
    search: true
    tools:
      - icon: github
        href: https://github.com/notmudge
        text: GitHub
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR-LINKEDIN/
        text: LinkedIn
        target: _blank
      - icon: envelope
        href: "mailto:you@example.com"
        text: Email
      - icon: bar-chart
        href: https://www.kaggle.com/alexmudge
        text: Kaggle
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: show
    include-after-body: sidebar-header.html  # keep this
