project:
  type: website

website:
  title: "Mudge"
  navbar:
    left:
      - text: "Blog"
        href: index.qmd
      - text: "CV"
        href: cv/index.qmd
  sidebar: false

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
    code-tools: true

# Enable Jupyter for Python code cells
jupyter: python3

# List posts on the homepage
listing:
  contents: posts
  sort: "date desc"
  type: default
