project:
  type: website
  resources:
    - sidebar-header.html
    - styles.css

website:
  title: "Mudge"
  sidebar:
    style: docked
    search: true
    collapse-level: 1

    # static icons row
    tools:
      - icon: github
        href: https://github.com/notmudge
        text: GitHub
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/notmudge/
        text: LinkedIn
        target: _blank
      - icon: envelope
        href: "mailto:mudge@protonmail.com"
        text: Email
      - icon: bar-chart
        href: https://www.kaggle.com/alexmudge
        text: Kaggle
        target: _blank

    contents:
      - text: "/"
        href: index.qmd

      - section: "ABOUT"
        contents:
          - text: "cv"
            href: cv/index.qmd

      - section: "LEARNING"
        contents:
          - text: "learning/python"
            href: learning/python.qmd
          - text: "learning/sql"
            href: learning/sql.qmd
          - text: "learning/powerbi"
            href: learning/powerbi.qmd
          - text: "learning/kaggle"
            href: learning/kaggle.qmd

      - section: "PROJECTS"
        contents:
          - text: "projects/index"
            href: projects/index.qmd
          - text: "projects/powerbi"
            href: projects/powerbi.qmd
          - text: "projects/python"
            href: projects/python.qmd

      - section: "BLOG"
        contents:
          - text: "blog/index"
            href: blog/index.qmd
          - text: "blog/reflections"
            href: blog/reflections.qmd

format:
  html:
    theme: darkly
    toc: true
    code-fold: show
    css: styles.css
    include-after-body: sidebar-header.html
