project:
  type: website

website:
  title: "Mudge â€” Data Science Blog"
  sidebar:
    style: "docked"      # "docked" keeps it fixed like in your image
    search: true
    tools:
      - icon: github
        href: https://github.com/notmudge
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR-LINKEDIN/
      - icon: envelope
        href: "mailto:you@example.com"
      - icon: bar-chart
        href: https://www.kaggle.com/alexmudge
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv/index.qmd
      - section: "Posts"
        contents: posts

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
